version: '3.4'
name: 'ms-professionals'

services:
  professionals:
    image: ${DOCKER_REGISTRY-}professionals
    hostname: professionals
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5003:5003"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5003
      - ASPNETCORE_HTTP_PORT=5003