version: '3.4'
name: 'apigateway'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_HTTP_PORT=5000